### ISSUE TITLE
I can't get a similar result as in the paper

### ISSUE THREAD

**Issue by Hx111222** [zbf1991/SCL#5] opened 2021-07-08 09:11 UTC
First of all, thanks for publishing your source code. However, We tried to train the code without making any changes. Torch==1.9.0 and other environment configurations also meet the requirements. However, after 200 epochs, the best Miou is just 60.88.
We use the Pascal-5i dataset, and the backbone is the resnet50 network, split=0. The best result we got was 60.88 instead of 63.0, which is written in the paper. We want to know what caused this result.

**Comment by zbf1991** [comment] 2021-07-14 02:45
Because someone else also cannot reproduce the results, I am not sure the reason, I will check again to see that if I have uploaded something wrong.

**Comment by zbf1991** [comment] 2021-07-14 03:50
I am re-running my code and I will reply to you as soon as possible.

**Comment by zbf1991** [comment] 2021-07-15 10:58
I will close this issue you can find a similar question in another issue. I have re-uploaded my 1-shot file, which is the current file I just re-tun. Although there is no difference. You can download this project and re-run it, 1080Ti with pytorch1.4 is okay (epoch 37 can reach 63.0). 2080ti with pytorch1.3/1.4 can also work. And it seems that pytorch1.3 is more stable. If you want to see the log file I can share it with you.

**Closed by zbf1991** 2021-07-15 10:58 UTC
